# Import ARO Cluster into ACM
# Required variables CLUSTER_NAME="clusername",TARGET_CLUSTER="target-cluster-url",TARGET_CLUSTER_TOKEN="sha256~xXxXxXxXxXxXxXxXxXxXxX,CLUSTER_ID=clusterid,ENABLE_OBSERVABILITY=true"
# https://aka.ms/yaml

trigger: none

pool:
  name: SelfHosted

container: quay.io/takinosh/aro-container:v1

steps:
- task: oc-setup@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ACMHUBCLUSTER'
- script: |
    oc status
    ./import-aro-cluster-to-acm.sh $(CLUSTER_NAME) $(TARGET_CLUSTER) $(TARGET_CLUSTER_TOKEN) $(CLUSTER_ID) $(ENABLE_OBSERVABILITY)
  displayName: 'Import Cluster into ACM'

