# Import ARO Cluster into ACM
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: SelfHosted

container: quay.io/takinosh/aro-container:v1

steps:
- task: oc-setup@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'ACMHUBCLUSTER'
- script: |
    oc status
    ./import-aro-cluster-to-acm.sh $(CLUSTER_NAME) $(TARGET_CLUSTER) $(TARGET_CLUSTER_TOKEN)
  displayName: 'Import Cluster into ACM'

