# Import ARO Cluster into ACM
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: SelfHosted

container:  'ubuntu-latest'

steps:
- task:  oc-setup@2
- script: |
    oc status
    cat import-aro-cluster-to-acm.sh 
  displayName: 'Import Cluster into ACM'
  