# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: SelfHosted

container: quay.io/takinosh/aro-container:v2

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(SUBSCRIPTION_ID)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'aro4-build.sh'
    arguments: '--register-resource-providers'
  displayName: 'Register the resource providers'
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(SUBSCRIPTION_ID)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'aro4-build.sh'
    arguments: '--configure-networking'
  displayName: 'Create a virtual network containing two empty subnets'