# Delete ARO cluster
# Delete ARO cluster with the following variables
# CLUSTER=,LOCATION=eastus,RESOURCEGROUP=,RAND=xxxxx,
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: SelfHosted

container: quay.io/takinosh/aro-container:v1

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(6)(1b84a886-709a-4b1b-98d6-d00f7f65452e)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'delete-aro-cluster.sh'
  displayName: 'Delete an Azure Red Hat OpenShift 4 cluster'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(6)(1b84a886-709a-4b1b-98d6-d00f7f65452e)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'clean-one-app-sp.sh'
  displayName: ' delete *all* Azure AD Apps and Service Principals'